name: CI

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Lint and Test with Node.js ${{ matrix.node }} on ${{ matrix.os }}
    strategy:
      matrix:
        node:
          - 18
          - 20
          - 22
          - 24
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
        env:
          # https://github.com/actions/setup-node/issues/531#issuecomment-1819151412
          SKIP_YARN_COREPACK_CHECK: 1

      - name: Install Dependencies
        run: yarn --immutable
        env:
          SKIP_YARN_COREPACK_CHECK: 1

      - name: Build, Lint and Test
        run: |
          yarn build
          yarn lint
          yarn test
        env:
          EFF_NO_LINK_RULES: true
          PARSER_NO_WATCH: true
          SKIP_YARN_COREPACK_CHECK: 1

      - name: Codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
