name: Release beta

on:
  pull_request:
    branches:
      - main
      - '!changeset-release/**'
  workflow_dispatch:
    inputs:
      version:
        description: specified version to be released
        required: true
      tag:
        description: optional specified npm tag to be released

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release_beta:
    name: Release Beta
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: lts/*
          cache: yarn

      - name: Install dependencies
        run: yarn --immutable

      - name: Set git info
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Release beta
        run: yarn release:beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PREVERSION_VERSION: ${{ github.event.inputs.version }}
          PREVERSION_TAG: ${{ github.event.inputs.tag }}
