name: Vercel Deploy

on:
  push:
    branches:
      - main
  pull_request_target: null

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Check Branch
        id: branch
        if: ${{ github.ref  == 'refs/heads/main' }}
        run: |
          echo "args=--prod" >> $GITHUB_OUTPUT
          echo "comment=false" >> $GITHUB_OUTPUT

      - name: Deploy
        uses: amondnet/vercel-action@888da851026e0573da056b061931bcb765a915c4 # v41.1.4
        with:
          vercel-args: ${{ steps.branch.outputs.args }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-comment: ${{ steps.branch.outputs.comment != 'false' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
